name: Flake8

on:
  push:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8
      - name: Install flake
        run: |
          python -m pip install --upgrade pip wheel
          pip install flake8
      - name: Run flake8
        run: |
          echo "::add-matcher::.github/matchers/flake8.json"
          flake8
          echo "::remove-matcher owner=flake8::"
